# Changes here will be overwritten by Copier
_commit: 0.1.11
_src_path: gh:12rambau/pypackage
author_email: pierrick.rambaud49@gmail.com
author_first_name: Pierrick
author_last_name: Rambaud
author_orcid: 0000-0001-8764-5749
creation_year: "2023"
github_repo_name: pytest-copie
github_user: 12rambau
project_name: pytest-copie
project_slug: pytest_copie
short_description: The pytest plugin for your copier templates 📒
