default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: "https://github.com/psf/black"
    rev: "22.3.0"
    hooks:
      - id: black
        stages: [commit]

  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v2.18.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.5.0"
    hooks:
      - id: nbstripout
        stages: [commit]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.215"
    hooks:
      - id: ruff
        stages: [commit]

  - repo: https://github.com/PyCQA/doc8
    rev: "v1.1.1"
    hooks:
      - id: doc8
        stages: [commit]

  - repo: https://github.com/FHPythonUtils/LicenseCheck
    rev: "2023.1.1"
    hooks:
      - id: licensecheck
        stages: [commit]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        stages: [commit]
        additional_dependencies:
          - tomli
